foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/Post.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/YearlyTotalPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java

2025.04.08 Add YearlyTotalPostCnt

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/Post.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/DailyTotalPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/MonthlyTotalPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/YearlyTotalPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java

Add Monthly,Daily TotalPostCnt/
Modify YearlyTotalPostCnt

Feature/total post montly&daily

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/Post.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/DailyNewPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/DailyTotalPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/MonthlyNewPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/MonthlyTotalPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/YearlyNewPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/YearlyTotalPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java

Add Yearly, Monthly, Daily NewPostCnt

Feature/new post(yearly&montly&daily)

---

.idea/compiler.xml
.idea/material_theme_project_new.xml
foodhubadmin_frontend/src/assets/css/adminChat.css
foodhubadmin_frontend/src/assets/css/adminDashboard.css
foodhubadmin_frontend/src/assets/css/adminLogin.css
foodhubadmin_frontend/src/assets/css/bannerManager.css
foodhubadmin_frontend/src/assets/css/errorPage.css
foodhubadmin_frontend/src/assets/css/footer.css
foodhubadmin_frontend/src/assets/css/header.css
foodhubadmin_frontend/src/assets/css/postReport.css
foodhubadmin_frontend/src/assets/css/profileView.css

Frontend 0408 2

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/DailyCategoryPostCnt.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/MonthlyCategoryPostCnt.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/YearlyCategoryPostCnt.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java

2025.04.09 Yearly,Monthly Category

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/DailyCategoryPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/MonthlyCategoryPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/YearlyCategoryPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java

Yearly,Monthly, Daily Category in backend

2025.04.09 Yearly,Monthly, Daily Category in backend

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/request/UserUpdateRequest.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/user/UserUpdateResponse.java

프로필상세보기, 패스워드변경, 회원정보변경ing

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/CommentsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java

2025.04.08

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/UserMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/User.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/request/UserChangePasswdRequest.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/request/UserUpdateRequest.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/user/UserProfileResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/user/UserUpdateResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/UserMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/UserMsService.java
foodhubadmin_frontend/src/components/ChangePasswd.jsx
foodhubadmin_frontend/src/components/ProfileView.jsx

마이페이지, 패스워드 변경 수정중

---

.idea/jpa.xml
.idea/material_theme_project_new.xml
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/CommentsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/CommentsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/CommentsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubadmin_frontend/package-lock.json
foodhubadmin_frontend/package.json
foodhubadmin_frontend/src/components/PostListTotal.jsx
foodhubadmin_frontend/src/components/UserStatus.jsx

post 데이터 월별, 일별 기간 설정

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/UserMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/User.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/UserMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/UserMsService.java
foodhubadmin_frontend/src/components/MemberList.jsx

MemberList -> List,delete fin./ update membership unfin.

2025.04.10

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/UserMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/Stats.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/StatsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/UserMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/UserMsService.java

userStatsEdit

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/CommentsController.java
foodhubadmin_frontend/src/components/CommentStats.jsx

new Comments -> searchDate frontend fin.

2025.04.11

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/DailyCategoryPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/MonthlyCategoryPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/YearlyCategoryPostCntResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/StatsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubadmin_frontend/src/components/CategoryPostList.jsx

categoryPost

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/CommentReportController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostReportController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/CommentReportService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostReportService.java
foodhubadmin_frontend/src/App.css
foodhubadmin_frontend/src/assets/css/postReport.css
foodhubadmin_frontend/src/components/CommentReport.jsx
foodhubadmin_frontend/src/components/MemberList.jsx
foodhubadmin_frontend/src/components/PostReport.jsx

게시글, 댓글 신고 목록 완성

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/CommentsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/CommentsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/CommentsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java
foodhubadmin_frontend/src/components/CommentStats.jsx

commentsEdit

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/UserMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/UserMsService.java
foodhubadmin_frontend/src/components/ChangePasswd.jsx
foodhubadmin_frontend/src/components/EditProfile.jsx
foodhubadmin_frontend/src/components/ProfileView.jsx

ProfileView & EditProfile에 이미지 이슈 완료

ProfileView & EditProfile에 이미지 이슈 완료

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/CommentsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/UserMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/StatsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/CommentsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/UserMsService.java
foodhubadmin_frontend/src/components/CommentStats.jsx

2025.04.14 Modify search Date(StatsRepository)

2025.04.14 Modify search Date(StatsRepository)

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/CommentsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/UserMsService.java

2025.04.14 Modify Service of Monthly

2025.04.14 Modify Service of Monthly

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/BannerController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/Banner.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/BannerService.java
foodhubadmin_frontend/src/assets/css/adminDashboard.css
foodhubadmin_frontend/src/assets/css/bannerManager.css
foodhubadmin_frontend/src/components/AdminDashboard.jsx
foodhubadmin_frontend/src/components/BannerManager.jsx

배너 추가, 수정 , 삭제 기능 완성

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/VisitorLogMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/User.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/VisitorLog.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/visitorLog/DailyVisitorLogResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/visitorLog/MonthlyVisitorLogResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/visitorLog/YearlyVisitorLogResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/VisitorLogMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/VisitorLogMsService.java
foodhubadmin_frontend/src/components/CategoryPostList.jsx
foodhubadmin_frontend/src/components/DashboardHome.jsx
foodhubadmin_frontend/src/components/PostListTotal.jsx
foodhubadmin_frontend/src/components/UserJoin.jsx
foodhubadmin_frontend/src/components/UserLeave.jsx
foodhubadmin_frontend/src/components/UserStatus.jsx
foodhubadmin_frontend/src/components/VisitorStats.jsx

2025.04.16 VisitorLog Chart fin.

2025.04.16 VisitorLog Chart fin.

---

foodhubadmin_frontend/package-lock.json
foodhubadmin_frontend/package.json
foodhubadmin_frontend/src/components/AdminChat.jsx
foodhubadmin_frontend/vite.config.js

reactChat수정중

---

foodhubadmin_frontend/src/App.jsx
foodhubadmin_frontend/src/components/AdminDashboard.jsx

맴버쉽 타입이 admin일 때 토큰 발행 추가

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/UserMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/StatsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/VisitorLogMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/VisitorLogMsService.java
foodhubadmin_frontend/src/components/CommentStats.jsx
foodhubadmin_frontend/src/components/ErrorPage.jsx
foodhubadmin_frontend/src/components/MemberList.jsx
foodhubadmin_frontend/src/components/UserJoin.jsx
foodhubadmin_frontend/src/components/UserLeave.jsx
foodhubadmin_frontend/src/components/UserStatus.jsx

2025.04.16 Modify VisitorLog Chart & error Page frontend

2025.04.16 Modify VisitorLog Chart & error Page frontend

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/AuthController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/CommentReportRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostReportRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/StatsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/VisitorLogMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/CommentReportService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostReportService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/VisitorLogMsService.java
foodhubadmin_frontend/src/components/DashboardHome.jsx
foodhubadmin_frontend/src/components/MemberList.jsx

Add Change of User Password in Member List

2025.04.17 Add Change of User Password

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/VisitorLogMsService.java
foodhubadmin_frontend/src/components/AdminChat.jsx
foodhubadmin_frontend/src/components/adminLogin.jsx

AdminChatEdit0417

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/StatsRepository.java
foodhubadmin_frontend/src/components/MemberList.jsx

2025.04.18 Modify passwd change in MemberList

2025.04.18 Modify passwd change in MemberList

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/VisitorLogMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/VisitorLogMsService.java
foodhubadmin_frontend/src/assets/css/adminChat.css
foodhubadmin_frontend/src/components/AdminChat.jsx

AdminChatFinal0418

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostMsRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java

edit0421-2

---

foodhubadmin_frontend/src/App.jsx
foodhubadmin_frontend/src/components/adminLogin.jsx

어디민 로그인 수정

---

foodhubadmin_frontend/index.html

2025.04.22 Modify Admin Page title

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/StatsSchedulerService.java
foodhubadmin_frontend/src/layout/Header.jsx

dropdown 이슈 수정

---

foodhubadmin_frontend/src/App.css
foodhubadmin_frontend/src/App.jsx
foodhubadmin_frontend/src/assets/css/adminDashboard.css

footer css 수정

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/UserMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/User.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/UserMsService.java
foodhubadmin_frontend/src/components/MemberList.jsx

2025.04.24 탈퇴 취소 추가

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/User.java

2025.04.25 탈퇴 취소 수정

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubadmin_frontend/src/components/PostReport.jsx

2025.04.25 PostReport 게시글 내용 추가

---

foodhubadmin_frontend/package-lock.json
foodhubadmin_frontend/package.json
foodhubadmin_frontend/src/components/PostReport.jsx

2025.04.25 PostReport 신고 게시글 내용 수정

---

foodhubadmin_frontend/src/components/AdminChat.jsx

채팅 중복처리 제거

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostMsController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/Post.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/User.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/PostResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostMsService.java
foodhubadmin_frontend/src/components/CommentReport.jsx
foodhubadmin_frontend/src/components/PostReport.jsx

2025.04.25 PostReport 팝업창 내용 및 스타일 수정

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/PostCreateController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/FileUpload.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/domain/Post.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/request/FileUploadRequest.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/request/PostCreateRequest.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/FileUploadRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/PostCreateRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/PostCreateService.java
foodhubadmin_frontend/package-lock.json
foodhubadmin_frontend/package.json
foodhubadmin_frontend/src/assets/css/createPost.css
foodhubadmin_frontend/src/components/AdminDashboard.jsx
foodhubadmin_frontend/src/components/AdminPostCreate.jsx
foodhubadmin_frontend/src/components/AdminPostList.jsx
foodhubadmin_frontend/src/routes/AppRouter.jsx

Create post 0425

---

foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/controller/AdminPostListController.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/dto/response/post/AdminPostListResponse.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/repository/AdminPostListRepository.java
foodhubAdmin_backend/src/main/java/com/application/foodhubAdmin/service/AdminPostListService.java
foodhubadmin_frontend/src/assets/css/postReport.css
foodhubadmin_frontend/src/components/AdminPostList.jsx
foodhubadmin_frontend/src/components/CommentReport.jsx
foodhubadmin_frontend/src/components/PostReport.jsx

관리자 게시글 목록 보기

---

foodhubAdmin_backend/src/test/java/com/application/foodhubAdmin/user/UserDaoTest.java
foodhubAdmin_backend/src/test/java/com/application/foodhubAdmin/user/UserMsServiceTest.java

UserDaoTest, UserMsServiceTest

UserDaoTest, UserMsServiceTest

---

foodhubadmin_frontend/src/components/ProfileView.jsx

회원정보 수정 -> 관리자 정보 수정

---

foodhubAdmin_backend/null5352addd-65f2-437f-ac7f-14150f5fabed.png
foodhubAdmin_backend/src/test/java/com/application/foodhubAdmin/adminPost/AdminPostListServiceTest.java
foodhubAdmin_backend/src/test/java/com/application/foodhubAdmin/adminPost/PostCreateServiceTest.java

Admin post test 0429

---

foodhubAdmin_backend/src/test/java/com/application/foodhubAdmin/user/UserRepositoryTest.java

UserRepositoryTest에서 프로필사진 변경 테스트 추가

UserRepositoryTest에서 프로필사진 변경 테스트 추가

---

foodhubadmin_frontend/src/components/chart/comment/CommentStats.jsx

2025.05.01 일별 댓글 x축 수정
